name: Backend Tests
on: 
    push:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.10'  
            -   name: Setup backend
                run: |
                    cd backend
                    python -m venv venv
                    source venv/bin/activate
                    pip install -r requirements.txt
            -   name: add credentials
                uses: 1arp/create-a-file-action@0.4.5
                with: 
                    path: 'backend'
                    file: admin_credentials.json
                    content: ${{secrets.BACKEND_CRED_JSON}}
            
            -   name: Run backend tests
                run: |
                    cd backend
                    source venv/bin/activate
                    PYTHONPATH=. pytest
            